#!/bin/zsh
# compdef ksw
_ksw() {
    local -a environments
    environments=(dev prd minikube heytea)

    _arguments "1:environment:(${environments[*]})"
    return 0
}

compdef _ksw ksw

# 设置补全样式
zstyle ':completion:*:*:ksw:*:descriptions' format '%F{blue}选择环境:%f'
