#!/bin/zsh

# compdef ksw
_ksw() {
    local -a environments
    # 从环境变量获取
    environments=(${(s: :)KSW_ENVIRONMENTS})

    _arguments "1:environment:(${environments[*]})"
    return 0
}

compdef _ksw ksw

# 设置补全样式
zstyle ':completion:*:*:ksw:*:descriptions' format '%F{blue}选择环境:%f'
